[package]
name = "aura-audit"
version = "0.1.0"
edition = "2021"

[dependencies]
core_affinity = "0.8.1"
arrow = { version = "54.2", features = ["prettyprint"] }
# lazy_static removed!
rusqlite = { version = "0.34", features = ["bundled"] } # Keep if you use DB later

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
